[workspace]
members = [
"amount-btc",
"main-rpc",
"zcash-rpc",

"switchboard-launcher",
"switchboard-config",
"switchboard-api",
"switchboard-rpc",
"switchboardd",
"switchboard-cli",
"switchboard-gui/src-tauri",
]
